[tool.pytest.ini_options]
pythonpath = "src"
testpaths = ["tests"]
norecursedirs = ["__pycache__", "*.egg-info", "build", "dist"]

[tool.mypy]
python_version = "3.13"
ignore_missing_imports = true
files = ["src/**/*.py", "tests/**/*.py"]